# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `date_by_example` gem.
# Please instead update this file by running `bin/tapioca gem date_by_example`.


# source://date_by_example//lib/date_by_example/date.rb#1
class Date
  include ::Comparable

  # source://date_by_example//lib/date_by_example/date.rb#2
  def by_example(example); end
end

# source://date_by_example//lib/date_by_example/version.rb#1
module DateByExample
  class << self
    # source://date_by_example//lib/date_by_example.rb#10
    def benchmark; end
  end
end

# source://date_by_example//lib/date_by_example/version.rb#2
DateByExample::VERSION = T.let(T.unsafe(nil), String)

# source://date_by_example//lib/date_by_example/date_time.rb#1
class DateTime < ::Date
  # source://date_by_example//lib/date_by_example/date_time.rb#2
  def by_example(example); end
end

# source://date_by_example//lib/date_by_example/example_formatter.rb#1
class ExampleFormatter
  # @return [ExampleFormatter] a new instance of ExampleFormatter
  #
  # source://date_by_example//lib/date_by_example/example_formatter.rb#4
  def initialize(reference); end

  # source://date_by_example//lib/date_by_example/example_formatter.rb#46
  def format(date); end

  # source://date_by_example//lib/date_by_example/example_formatter.rb#42
  def format_string; end

  # Returns the value of attribute reference.
  #
  # source://date_by_example//lib/date_by_example/example_formatter.rb#2
  def reference; end

  # Sets the attribute reference
  #
  # @param value the value to set the attribute reference to.
  #
  # source://date_by_example//lib/date_by_example/example_formatter.rb#2
  def reference=(_arg0); end
end

# source://date_by_example//lib/date_by_example/example_formatter.rb#9
ExampleFormatter::FORMATS = T.let(T.unsafe(nil), Hash)

# source://date_by_example//lib/date_by_example/example_formatter.rb#40
ExampleFormatter::FORMAT_MATCHER = T.let(T.unsafe(nil), Regexp)

# source://date_by_example//lib/date_by_example/time.rb#1
class Time
  include ::Comparable

  # source://date_by_example//lib/date_by_example/time.rb#2
  def by_example(example); end
end
